function OpportunityDetails({ opportunity, isSaved, onSave, onTrackApplication, onBack }) {
  return (
    <section className="panel opportunity-details"><div className="details-toolbar"><button className="quiet-button" type="button" onClick={onBack}>&lt;- Back to results</button><span className="details-label">Demo opportunity record</span></div><div className="details-heading"><div className="company-logo">{opportunity.company.slice(0, 2).toUpperCase()}</div><div><p className="eyebrow accent-eyebrow">{opportunity.company}</p><h2>{opportunity.title}</h2><p>{opportunity.location} · {opportunity.workMode} · {opportunity.employmentType}</p></div></div><div className="details-actions"><button className="primary-button" type="button" onClick={() => onTrackApplication(opportunity)}>Track application <span>+</span></button><button className={isSaved ? 'secondary-button save-opportunity-active' : 'secondary-button'} type="button" onClick={() => onSave(opportunity)}>{isSaved ? 'Remove saved opportunity' : 'Save opportunity'}</button><a className="quiet-button" href={opportunity.applicationUrl} target="_blank" rel="noreferrer">Open demo opportunity <span>-&gt;</span></a></div><div className="details-facts"><span><strong>Salary</strong>{formatSalary(opportunity)}</span><span><strong>Experience</strong>{opportunity.experienceLevel}</span><span><strong>Posted</strong>{formatDate(opportunity.postedDate)}</span><span><strong>Deadline</strong>{opportunity.applicationDeadline ? formatDate(opportunity.applicationDeadline) : 'Not listed'}</span></div><div className="details-grid"><div><h3>About the opportunity</h3><p>{opportunity.description}</p><h3>Responsibilities</h3><ul>{opportunity.responsibilities.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h3>Required skills</h3><div className="research-skills details-skills">{opportunity.requiredSkills.map((skill) => <span key={skill}>{skill}</span>)}</div><h3>Preferred skills</h3><div className="research-skills details-skills">{opportunity.preferredSkills.map((skill) => <span key={skill}>{skill}</span>)}</div><p className="details-note">Opening this link is a demo action. CareerPilot has not submitted an application.</p></div></div></section>
  )
}

function formatSalary(opportunity) { return `${opportunity.currency} ${(opportunity.salaryMin / 100000).toFixed(0)}L - ${(opportunity.salaryMax / 100000).toFixed(0)}L` }
function formatDate(value) { return new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)) }

export default OpportunityDetails
