export const demoOpportunities = [
  {
    id: 'opp-java-01', title: 'Java Full Stack Developer', company: 'Northstar Labs', location: 'Remote / Jaipur, India', workMode: 'Remote', employmentType: 'Full-time', experienceLevel: 'Mid Level', salaryMin: 1100000, salaryMax: 1700000, currency: 'INR', skills: ['Java', 'Spring Boot', 'Angular', 'AWS'], description: 'Build reliable customer experiences across a modern Java platform used by teams around the world.', responsibilities: ['Design and ship full stack product features', 'Collaborate with product and design partners', 'Improve platform reliability and developer experience'], requiredSkills: ['Java', 'Spring Boot', 'REST APIs'], preferredSkills: ['Angular', 'AWS', 'Docker'], postedDate: '2026-09-18', applicationDeadline: '2026-10-20', applicationUrl: 'https://example.com/opportunities/java-full-stack' },
  {
    id: 'opp-ai-02', title: 'AI Engineer', company: 'SignalWorks', location: 'Bengaluru, India', workMode: 'Hybrid', employmentType: 'Full-time', experienceLevel: 'Mid Level', salaryMin: 1800000, salaryMax: 2800000, currency: 'INR', skills: ['Python', 'PyTorch', 'LLMs', 'AWS'], description: 'Help turn applied machine learning research into dependable features for enterprise teams.', responsibilities: ['Prototype and evaluate language model workflows', 'Build data and model evaluation pipelines', 'Partner with engineers to productionize experiments'], requiredSkills: ['Python', 'Machine Learning', 'LLMs'], preferredSkills: ['PyTorch', 'AWS', 'MLOps'], postedDate: '2026-09-16', applicationDeadline: '', applicationUrl: 'https://example.com/opportunities/ai-engineer' },
  {
    id: 'opp-genai-03', title: 'Generative AI Developer', company: 'Orbit Cloud', location: 'Remote / India', workMode: 'Remote', employmentType: 'Contract', experienceLevel: 'Entry Level', salaryMin: 900000, salaryMax: 1400000, currency: 'INR', skills: ['Python', 'LangChain', 'Prompt Design', 'React'], description: 'Create thoughtful AI-assisted workflows and interfaces for a fast-moving cloud product team.', responsibilities: ['Develop prompt and retrieval experiments', 'Build lightweight React prototypes', 'Document learnings for the wider engineering team'], requiredSkills: ['Python', 'Prompt Design', 'APIs'], preferredSkills: ['LangChain', 'React', 'Vector Databases'], postedDate: '2026-09-14', applicationDeadline: '2026-10-05', applicationUrl: 'https://example.com/opportunities/generative-ai' },
  {
    id: 'opp-python-04', title: 'Python Developer', company: 'BluePeak Analytics', location: 'Pune, India', workMode: 'On-site', employmentType: 'Full-time', experienceLevel: 'Entry Level', salaryMin: 700000, salaryMax: 1100000, currency: 'INR', skills: ['Python', 'Django', 'PostgreSQL', 'Git'], description: 'Join a small product team building analytics tools that help businesses make better decisions.', responsibilities: ['Implement backend services and integrations', 'Write tests and maintain technical documentation', 'Work with analysts to clarify data workflows'], requiredSkills: ['Python', 'Django', 'SQL'], preferredSkills: ['PostgreSQL', 'Docker', 'React'], postedDate: '2026-09-12', applicationDeadline: '', applicationUrl: 'https://example.com/opportunities/python-developer' },
  {
    id: 'opp-backend-05', title: 'Backend Developer', company: 'Vercel Systems', location: 'New York, NY / Remote', workMode: 'Hybrid', employmentType: 'Full-time', experienceLevel: 'Senior Level', salaryMin: 2200000, salaryMax: 3600000, currency: 'INR', skills: ['Node.js', 'TypeScript', 'PostgreSQL', 'AWS'], description: 'Own backend systems that make developer tools faster, clearer, and more dependable.', responsibilities: ['Lead service design from idea to operation', 'Set standards for observability and testing', 'Mentor engineers across the platform group'], requiredSkills: ['Node.js', 'TypeScript', 'Distributed Systems'], preferredSkills: ['PostgreSQL', 'AWS', 'Kubernetes'], postedDate: '2026-09-10', applicationDeadline: '2026-10-12', applicationUrl: 'https://example.com/opportunities/backend-developer' },
  {
    id: 'opp-software-06', title: 'Software Engineer', company: 'Arc Studio', location: 'Remote / Bengaluru, India', workMode: 'Remote', employmentType: 'Internship', experienceLevel: 'Entry Level', salaryMin: 450000, salaryMax: 700000, currency: 'INR', skills: ['JavaScript', 'React', 'Git', 'Testing'], description: 'Learn in public with a product-minded team that values clear thinking and careful craft.', responsibilities: ['Build accessible product interfaces', 'Pair with experienced engineers', 'Contribute to testing and release notes'], requiredSkills: ['JavaScript', 'React', 'Git'], preferredSkills: ['TypeScript', 'Testing', 'CSS'], postedDate: '2026-09-08', applicationDeadline: '2026-10-01', applicationUrl: 'https://example.com/opportunities/software-engineer' },
  {
    id: 'opp-ml-07', title: 'Machine Learning Engineer', company: 'Cedar Robotics', location: 'Hyderabad, India', workMode: 'On-site', employmentType: 'Full-time', experienceLevel: 'Senior Level', salaryMin: 2400000, salaryMax: 4000000, currency: 'INR', skills: ['Python', 'TensorFlow', 'Computer Vision', 'GCP'], description: 'Develop production machine learning systems that help robots understand changing environments.', responsibilities: ['Train and deploy computer vision models', 'Build reliable data collection loops', 'Collaborate with robotics and infrastructure teams'], requiredSkills: ['Python', 'Machine Learning', 'Computer Vision'], preferredSkills: ['TensorFlow', 'GCP', 'C++'], postedDate: '2026-09-05', applicationDeadline: '', applicationUrl: 'https://example.com/opportunities/ml-engineer' },
  {
    id: 'opp-fullstack-08', title: 'Full Stack Developer', company: 'BrightPath Learning', location: 'Remote / Jaipur, India', workMode: 'Remote', employmentType: 'Part-time', experienceLevel: 'Mid Level', salaryMin: 800000, salaryMax: 1300000, currency: 'INR', skills: ['Java', 'React', 'Spring Boot', 'PostgreSQL'], description: 'Help learners build the tools and confidence they need for the next stage of their careers.', responsibilities: ['Deliver features across web and API layers', 'Translate learner feedback into product improvements', 'Keep code quality and performance visible'], requiredSkills: ['Java', 'React', 'REST APIs'], preferredSkills: ['Spring Boot', 'PostgreSQL', 'AWS'], postedDate: '2026-09-02', applicationDeadline: '2026-09-30', applicationUrl: 'https://example.com/opportunities/full-stack' },
]

export const employmentTypes = ['Full-time', 'Part-time', 'Contract', 'Internship']
export const workModes = ['Remote', 'Hybrid', 'On-site']
export const experienceLevels = ['Entry Level', 'Mid Level', 'Senior Level']
export const salaryRanges = [
  { value: 'any', label: 'Any salary' },
  { value: 'under-10', label: 'Under INR 10L', max: 1000000 },
  { value: '10-20', label: 'INR 10L - 20L', min: 1000000, max: 2000000 },
  { value: 'over-20', label: 'Over INR 20L', min: 2000000 },
]

export const allSkills = [...new Set(demoOpportunities.flatMap((opportunity) => opportunity.skills))].sort()