import OutreachFilters from './OutreachFilters'

function OutreachHistory({ records, filter, search, onFilter, onSearch, onEdit, onDelete }) {
  return <section className="panel outreach-history-panel"><div className="section-heading"><div><p className="eyebrow accent-eyebrow">Conversation log</p><h2>Outreach history</h2></div><span className="content-count">{records.length} shown</span></div><div className="history-tools"><input className="outreach-search" value={search} onChange={(event) => onSearch(event.target.value)} placeholder="Search name, company, or message..." aria-label="Search outreach history" /><OutreachFilters active={filter} onChange={onFilter} /></div>{records.length ? <div className="outreach-history-list">{records.map((record) => <article className="outreach-history-row" key={record.id}><div className="contact-avatar">{record.contact.name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase()}</div><div className="history-copy"><div className="history-title"><strong>{record.contact.name}</strong><span className={`outreach-status-badge status-${record.status.toLowerCase().replace(/[^a-z]+/g, '-')}`}>{record.status}</span></div><p>{record.contact.company} · {record.messageType}{record.opportunity ? ` · ${record.opportunity.title}` : ''}</p><div className="history-message">{record.message}</div><small>Created {formatDate(record.createdAt)}{record.followUpDate ? ` · Follow-up ${formatDate(record.followUpDate)}` : ''} · {countWords(record.message)} words · {record.message.length} characters</small></div><div className="history-actions"><button className="small-action" type="button" onClick={() => onEdit(record)}>Edit</button><button className="remove-button" type="button" onClick={() => onDelete(record.id)}>Delete</button></div></article>)}</div> : <p className="empty-copy">No outreach records match this view.</p>}</section>
}

function formatDate(value) { return new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)) }
function countWords(value) { return value.trim() ? value.trim().split(/\s+/).length : 0 }

export default OutreachHistory
